interface IEntryMock {
  time:Date,
  productName:string,
  subCategory:string,
  price:number,
  productLink:string,
}

export const entryMock:IEntryMock[] = [
  {time:new Date('2025-03-17'),
    productName:'코카콜라 제로',
    subCategory:'청량・탄산음료',
    price:1900,
    productLink:'www.example.com',
  },
  {time:new Date('2025-03-17'),
    productName:'코카콜라 제로',
    subCategory:'청량・탄산음료',
    price:1900,
    productLink:'www.example.com',
  },
  {time:new Date('2025-03-17'),
    productName:'코카콜라 제로',
    subCategory:'청량・탄산음료',
    price:1900,
    productLink:'www.example.com',
  },
  {time:new Date('2025-03-17'),
    productName:'코카콜라 제로',
    subCategory:'청량・탄산음료',
    price:1900,
    productLink:'www.example.com',
  },
  {time:new Date('2025-03-17'),
    productName:'코카콜라 제로',
    subCategory:'청량・탄산음료',
    price:1900,
    productLink:'www.example.com',
  },
  {time:new Date('2025-03-17'),
    productName:'코카콜라 제로',
    subCategory:'청량・탄산음료',
    price:1900,
    productLink:'www.example.com',
  },
  {time:new Date('2025-03-17'),
    productName:'코카콜라 제로',
    subCategory:'청량・탄산음료',
    price:1900,
    productLink:'www.example.com',
  },
  {time:new Date('2025-03-17'),
    productName:'코카콜라 제로',
    subCategory:'청량・탄산음료',
    price:1900,
    productLink:'www.example.com',
  },
]